"""
Table extractor module for ARneuro.

This module extracts tables from markdown documents.
"""

import os
import re
import json
from typing import List, Dict, Optional, Tuple, Any
from core.logger import get_logger

logger = get_logger(__name__)


class TableExtractor:
    """
    Extract tables from markdown documents.
    """
    
    def __init__(self, config: Optional[Dict] = None):
        """
        Initialize the table extractor.
        
        Args:
            config: Configuration dictionary
        """
        self.config = config or {}
    
    def extract_tables_from_markdown(self, 
                                    markdown_file: str,
                                    context_lines: int = 5) -> List[Dict]:
        """
        Extract tables from markdown file with context.
        
        Args:
            markdown_file: Path to markdown file
            context_lines: Number of context lines before and after table
            
        Returns:
            List[Dict]: List of table information dictionaries
        """
        if not os.path.exists(markdown_file):
            raise FileNotFoundError(f"Markdown file not found: {markdown_file}")
        
        logger.info(f"Extracting tables from: {markdown_file}")
        
        with open(markdown_file, 'r', encoding='utf-8') as f:
            md_text = f.read()
        
        return self.extract_tables_from_text(md_text, context_lines)
    
    def extract_tables_from_text(self, 
                                md_text: str,
                                context_lines: int = 5) -> List[Dict]:
        """
        Extract tables from markdown text with context.
        
        Args:
            md_text: Markdown text
            context_lines: Number of context lines before and after table
            
        Returns:
            List[Dict]: List of table information dictionaries
        """
        lines = md_text.split('\n')
        tables_info = []
        
        i = 0
        while i < len(lines):
            line = lines[i]
            
            # Check if line starts a markdown table (starts and ends with pipe)
            if line.strip().startswith('|') and line.strip().endswith('|'):
                table_start = i
                table_lines = []
                
                # Collect all consecutive table rows
                while i < len(lines) and (lines[i].strip().startswith('|') or lines[i].strip() == ''):
                    table_lines.append(lines[i])
                    i += 1
                
                # Join table lines
                table_text = '\n'.join(table_lines)
                
                # Get context before table
                before_start = max(0, table_start - context_lines)
                before_context = '\n'.join(lines[before_start:table_start])
                
                # Get context after table
                after_end = min(len(lines), i + context_lines)
                after_context = '\n'.join(lines[i:after_end])
                
                # Full context
                full_context = f"{before_context}\n[TABLE {len(tables_info) + 1}]\n{after_context}"
                
                # Parse table structure
                table_structure = self._parse_table_structure(table_text)
                
                tables_info.append({
                    'table_index': len(tables_info),
                    'table_text': table_text,
                    'table_structure': table_structure,
                    'before_context': before_context,
                    'after_context': after_context,
                    'full_context': full_context,
                    'num_rows': table_structure['num_rows'],
                    'num_columns': table_structure['num_columns'],
                    'has_header': table_structure['has_header'],
                    'header_row': table_structure['header_row']
                })
            else:
                i += 1
        
        logger.info(f"Extracted {len(tables_info)} tables from text")
        return tables_info
    

    def extract_tables_from_structured_content(self,
                                             structured_content: Dict[str, Any],
                                             source_markdown: Optional[str] = None,
                                             context_lines: int = 5) -> List[Dict]:
        """Extract table metadata from `*_structured_content.json` payload.

        Args:
            structured_content: Structured content generated by TextProcessingPipeline
            source_markdown: Optional original markdown file for context recovery
            context_lines: Number of context lines around table line_start

        Returns:
            List[Dict]: Normalized table dictionaries compatible with legacy pipeline
        """
        table_items = structured_content.get('Tables', []) or []
        if not isinstance(table_items, list):
            logger.warning("structured_content['Tables'] is not a list, returning empty table list")
            return []

        markdown_lines = []
        if source_markdown and os.path.exists(source_markdown):
            with open(source_markdown, 'r', encoding='utf-8') as f:
                markdown_lines = f.read().split('\n')

        tables_info: List[Dict] = []
        for idx, table_item in enumerate(table_items):
            if isinstance(table_item, dict):
                table_text = table_item.get('content', '')
                table_id = table_item.get('id', f'table_{idx + 1}')
                line_start = int(table_item.get('line_start', 0) or 0)
            else:
                table_text = str(table_item)
                table_id = f'table_{idx + 1}'
                line_start = 0

            table_structure = self._parse_table_structure(table_text)

            before_context = ''
            after_context = ''
            if markdown_lines and line_start > 0:
                start_idx = max(0, line_start - 1)
                before_context = '\n'.join(markdown_lines[max(0, start_idx - context_lines):start_idx])
                table_height = len([ln for ln in table_text.split('\n') if ln.strip()])
                after_context = '\n'.join(markdown_lines[start_idx + table_height:start_idx + table_height + context_lines])

            full_context = f"{before_context}\n[TABLE {idx + 1}]\n{after_context}"
            tables_info.append({
                'table_index': idx,
                'table_id': table_id,
                'line_start': line_start if line_start > 0 else None,
                'table_text': table_text,
                'table_structure': table_structure,
                'before_context': before_context,
                'after_context': after_context,
                'full_context': full_context,
                'num_rows': table_structure['num_rows'],
                'num_columns': table_structure['num_columns'],
                'has_header': table_structure['has_header'],
                'header_row': table_structure['header_row']
            })

        logger.info(f"Extracted {len(tables_info)} tables from structured content")
        return tables_info

    def _parse_table_structure(self, table_text: str) -> Dict:
        """
        Parse table structure from markdown text.
        
        Args:
            table_text: Markdown table text
            
        Returns:
            Dict: Table structure information
        """
        lines = [line.strip() for line in table_text.split('\n') if line.strip()]
        
        if not lines:
            return {
                'num_rows': 0,
                'num_columns': 0,
                'has_header': False,
                'header_row': None,
                'data_rows': []
            }
        
        # Find separator row (contains only dashes, colons, and pipes)
        separator_idx = -1
        for i, line in enumerate(lines):
            # Remove pipes and check if only dashes, colons, and spaces remain
            clean_line = line.replace('|', '').strip()
            if re.match(r'^[:\-\s]+$', clean_line):
                separator_idx = i
                break
        
        # Parse headers
        has_header = separator_idx > 0
        header_row = None
        
        if has_header:
            header_line = lines[separator_idx - 1]
            headers = [cell.strip() for cell in header_line.split('|') if cell.strip()]
        else:
            # Use first row as headers
            header_line = lines[0]
            headers = [cell.strip() for cell in header_line.split('|') if cell.strip()]
        
        # Parse data rows
        data_start = separator_idx + 1 if separator_idx >= 0 else 1
        data_rows = []
        
        for i in range(data_start, len(lines)):
            if '|' in lines[i]:
                cells = [cell.strip() for cell in lines[i].split('|') if cell.strip()]
                if len(cells) == len(headers):
                    data_rows.append(cells)
        
        return {
            'num_rows': len(data_rows),
            'num_columns': len(headers),
            'has_header': has_header,
            'header_row': headers,
            'data_rows': data_rows
        }
    
    def filter_tables_by_content(self, 
                                tables_info: List[Dict],
                                keywords: List[str]) -> List[Dict]:
        """
        Filter tables by content keywords.
        
        Args:
            tables_info: List of table information dictionaries
            keywords: List of keywords to search for
            
        Returns:
            List[Dict]: Filtered tables
        """
        filtered_tables = []
        
        for table_info in tables_info:
            table_text = table_info['table_text'].lower()
            context_text = table_info['full_context'].lower()
            
            # Check if any keyword appears in table or context
            for keyword in keywords:
                if keyword.lower() in table_text or keyword.lower() in context_text:
                    filtered_tables.append(table_info)
                    break
        
        logger.info(f"Filtered {len(filtered_tables)} tables matching keywords: {keywords}")
        return filtered_tables
    
    def categorize_tables(self,
                        tables_info: List[Dict],
                        llm_client=None,
                        model_name: str = 'deepseek-chat',
                        llm_client_type: str = 'deepseek') -> Dict[str, List[Dict]]:
        """Categorize tables by content type using LLM only (no keyword matching)."""
        if llm_client is None:
            raise ValueError("LLM client is required for table categorization")
        categories = {
            'brain_activation': [],
            'demographic': [],
            'statistical': [],
            'methodological': [],
            'other': []
        }

        for table_info in tables_info:
            table_text = table_info.get('table_text', '')
            context_text = table_info.get('full_context', '')
            try:
                label = self._categorize_table_llm(
                    table_text=table_text,
                    context_text=context_text,
                    llm_client=llm_client,
                    model_name=model_name
                )
            except Exception as e:
                logger.warning(f"LLM categorization failed for table {table_info.get('table_index')}: {e}")
                label = "other"

            if label in categories:
                categories[label].append(table_info)
            else:
                categories['other'].append(table_info)

        for category, tables in categories.items():
            logger.info(f"Category '{category}': {len(tables)} tables")
        return categories

    def _categorize_table_llm(self,
                              table_text: str,
                              context_text: str,
                              llm_client,
                              model_name: str = 'deepseek-chat') -> str:
        """Use staged LLM checks to classify table type."""
        lines = [ln for ln in table_text.split('\n') if ln.strip()]
        if not lines:
            return "other"

        stage1_lines = lines
        if len(lines) > 10:
            stage1_lines = lines[:5] + ['...'] + lines[-5:]

        stage1_prompt = "\n".join(stage1_lines)
        stage1_result = self._llm_table_category_decision(
            llm_client=llm_client,
            model_name=model_name,
            table_snippet=stage1_prompt,
            context_text=context_text,
            require_need_full=(len(lines) > 10)
        )

        if stage1_result.get('category') == 'brain_activation':
            return 'brain_activation'

        if len(lines) <= 10:
            return stage1_result.get('category', 'other')

        if not stage1_result.get('need_full_scan', False):
            return stage1_result.get('category', 'other')

        chunk_size = 10
        for i in range(0, len(lines), chunk_size):
            chunk = "\n".join(lines[i:i+chunk_size])
            chunk_result = self._llm_table_category_decision(
                llm_client=llm_client,
                model_name=model_name,
                table_snippet=chunk,
                context_text=context_text if i == 0 else '',
                require_need_full=False
            )
            if chunk_result.get('category') == 'brain_activation':
                return 'brain_activation'
        return stage1_result.get('category', 'other')

    def _llm_table_category_decision(self,
                                  llm_client,
                                  model_name: str,
                                  table_snippet: str,
                                  context_text: str,
                                  require_need_full: bool) -> Dict[str, Any]:
        """Single LLM decision call for table categorization."""
        prompt_suffix = 'Include need_full_scan in JSON.' if require_need_full else 'Set need_full_scan to false.'
        system_prompt = f"""You classify neuroscience paper tables into one label:
brain_activation, demographic, statistical, methodological, other.
Use brain_activation only when explicit brain coordinates are present (x/y/z columns or MNI/Talairach/peak xyz triplets).
Return JSON only: {{"category":"one_label","need_full_scan":true|false}}. {prompt_suffix}"""

        user_prompt = f"""Table snippet:
{table_snippet}

Context (if any):
{context_text}"""
        response = llm_client.chat.completions.create(
            model=model_name,
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_prompt}
            ],
            temperature=0,
            response_format={"type": "json_object"},
            max_tokens=300
        )
        result = json.loads(response.choices[0].message.content)
        category = str(result.get('category', 'other')).strip().lower()
        if category not in {'brain_activation', 'demographic', 'statistical', 'methodological', 'other'}:
            category = 'other'
        return {
            'category': category,
            'need_full_scan': bool(result.get('need_full_scan', False))
        }
    
    def save_table_extraction_results(self, 
                                     tables_info: List[Dict],
                                     output_dir: str,
                                     filename: str = "table_extraction.json") -> str:
        """
        Save table extraction results to JSON file.
        
        Args:
            tables_info: List of table information dictionaries
            output_dir: Output directory
            filename: Output filename
            
        Returns:
            str: Path to saved file
        """
        import os
        
        os.makedirs(output_dir, exist_ok=True)
        
        # Prepare results for JSON serialization
        results = []
        for table_info in tables_info:
            # Create a serializable copy
            table_result = {
                'table_index': table_info['table_index'],
                'table_text': table_info['table_text'],
                'table_structure': table_info['table_structure'],
                'before_context': table_info['before_context'],
                'after_context': table_info['after_context'],
                'num_rows': table_info['num_rows'],
                'num_columns': table_info['num_columns'],
                'has_header': table_info['has_header']
            }
            results.append(table_result)
        
        output_path = os.path.join(output_dir, filename)
        with open(output_path, 'w', encoding='utf-8') as f:
            json.dump({
                'total_tables': len(results),
                'tables': results
            }, f, indent=2, ensure_ascii=False)
        
        logger.info(f"Saved table extraction results to: {output_path}")
        return output_path
    
    def export_tables_to_csv(self, 
                            tables_info: List[Dict],
                            output_dir: str) -> List[str]:
        """
        Export tables to CSV files.
        
        Args:
            tables_info: List of table information dictionaries
            output_dir: Output directory
            
        Returns:
            List[str]: List of paths to saved CSV files
        """
        import os
        import pandas as pd
        
        os.makedirs(output_dir, exist_ok=True)
        
        saved_files = []
        
        for table_info in tables_info:
            table_idx = table_info['table_index']
            structure = table_info['table_structure']
            
            # Create DataFrame from table structure
            if structure['data_rows']:
                df = pd.DataFrame(
                    structure['data_rows'],
                    columns=structure['header_row'] if structure['has_header'] else None
                )
                
                # Save to CSV
                csv_path = os.path.join(output_dir, f"table_{table_idx + 1}.csv")
                df.to_csv(csv_path, index=False)
                saved_files.append(csv_path)
                
                # Save metadata
                metadata = {
                    'table_index': table_idx,
                    'num_rows': len(df),
                    'num_columns': len(df.columns),
                    'columns': list(df.columns),
                    'context_before': table_info['before_context'],
                    'context_after': table_info['after_context']
                }
                
                metadata_path = os.path.join(output_dir, f"table_{table_idx + 1}_metadata.json")
                with open(metadata_path, 'w', encoding='utf-8') as f:
                    json.dump(metadata, f, indent=2, ensure_ascii=False)
        
        logger.info(f"Exported {len(saved_files)} tables to CSV files in: {output_dir}")
        return saved_files
